CREATE DATABASE sys_reserva;

use sys_reserva;

CREATE TABLE tipos_usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_tipo VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE tipos_sala (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_tipo VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE status_reserva (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_status VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status BOOLEAN DEFAULT FALSE,
  tipo_usuarioId INT NOT NULL,
  CONSTRAINT fk_usuario_tipo FOREIGN KEY (tipo_usuarioId) REFERENCES tipos_usuario(id)
);

CREATE TABLE salas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  capacidade INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  tipo_salaId INT NOT NULL,
  CONSTRAINT fk_sala_tipo FOREIGN KEY (tipo_salaId) REFERENCES tipos_sala(id)
);

CREATE TABLE reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dataInicio DATETIME NOT NULL,
  dataFim DATETIME NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  observacao VARCHAR(255),
  usuarioId INT NOT NULL,
  salaId INT NOT NULL,
  statusReservaId INT NOT NULL,
  CONSTRAINT fk_reserva_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id),
  CONSTRAINT fk_reserva_sala FOREIGN KEY (salaId) REFERENCES salas(id),
  CONSTRAINT fk_reserva_status FOREIGN KEY (statusReservaId) REFERENCES status_reserva(id)
);
